server:
  port: 8088

spring:
  application:
    name: PAYMENT-SERVICE

razorpay:
  key-id: rzp_test_T0QfAmUyD2FIb7
  key-secret: mLjLaZTRNJ3XmfIFrcLg4Bj8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/